### ISSUE TITLE
Liste alphabetisch ordnen

### ISSUE THREAD

**Issue by JMD49591** [ErikWegner/wamytm#14]
Würde mehr Übersichtlichkeit rein bringen. Bei einer großen Liste ist es doch etwas anstrengend den Namen eines Kollegens zu finden.

**Comment by ClickKlack** [comment]
Ist das Issue wirklich umgesetzt? Ich kann keine Sortierung erkennen. Bei der Masse an Personen ist es gerade extrem unübersichtlich. :-(
