### ISSUE TITLE
Eintrags-Administration für andere User

### ISSUE THREAD

**Issue by ClickKlack** [ErikWegner/wamytm#20]
Es wäre sehr hilfreich, wenn man eine Berechtigung vergeben könnte, dass man auch für andere Nutzer Einträge vornehmen, oder diese ändern könnte.

Es passiert leider, dass Kolelgen aufgrund von Erkrankung keine Anpassung ihrer Einträge vornehmen können. Im Sinne der Teaminformation wäre es schön, wenn man diese durch andere Kollegen auf abwesend setzten könnte. Aktuell hält der Korporator für diese Kollegen eine Falschinformation die nicht korrigiert werden kann.

**Comment by ErikWegner** [comment]
Enthalten in Version 013
