### ISSUE TITLE
Fehlerhafte Anzeige in Wochen- und 3-Monatsvorschau

### ISSUE THREAD

**Issue by cl1771** [ErikWegner/wamytm#25]
Sowohl in der Wochen- als auch in der 3-Monatsvorschau werden eingepflegte Einträge nicht korrekt angezeigt (Bsp.: Mobiles Arbeiten wurde vom 17.08. bis 28.08. eingetragen. In der 3-Monatsvorschau wird allerdings "im Büro" angezeigt).

**Comment by ErikWegner** [comment]
Tritt das Problem noch auf?

**Comment by ErikWegner** [comment]
Keine Rückmeldung, Ticket wird geschlossen
