### ISSUE TITLE
Link zum Bugeintrag/Featurerequest

### ISSUE THREAD

**Issue by blueeagleeye** [ErikWegner/wamytm#31]
Es wäre gut, wenn es aus dem Korporator direkt einen Link hierher zum Github-Projekt für die Erstellung von Bug-Reports oder Feature-Requests geben würde

**Comment by ErikWegner** [comment]
Der Link zum Repository befindet sich in der [footer.html](https://github.com/ErikWegner/wamytm/blob/54516c72eb74169838928e507d743311e7aad82c/src/wamytmapp/templates/wamytmapp/footer.html#L6)-Datei
