### ISSUE TITLE
Benutzerfreundlichkeit Datumsauswahl

### ISSUE THREAD

**Issue by ClickKlack** [ErikWegner/wamytm#7]
In der Eintragungsmaske für einen Zeitraum sollte der Datumspicker für das Ende in den Monat des Beginns (wenn ausgewählt) springen, anstelle in den aktuellen Monat.

Wenn ich z.B. jetzt einen Eintrag für August mache, muss ich bei Beginn und Ende durch die Monate scrollen. Ein Ende vor dem Beginn macht aber keinen Sinn, es wäre also schön wenn mir beim Ende gleich der August angeboten wird.

![grafik](https://user-images.githubusercontent.com/60615857/73822749-126f4e00-47f7-11ea-9649-7efce07380a0.png)

**Comment by ErikWegner** [comment]
Umgesetzt
